import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react";
import LoginButton from "../components/auth/LoginButton";
import { useEffect } from "react";
import { object } from "zod";

const queryOptions = {
  retry: false,
};

const Home: NextPage = () => {
  const { data: session } = useSession();
  const { data, isLoading, error } = trpc.useQuery(
    ["question.hello", { text: "from tRPC" }],
    queryOptions
  );
  const sesion = trpc.useQuery(["question.getSession"], queryOptions);
  const secret = trpc.useQuery(["question.getSecretMessage"], queryOptions);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LoginButton />

        <h1>
          Create <span>T3</span> App
        </h1>

        {error ? (
          <div>Error: {error.message}</div>
        ) : (
          <div>
            <div>{data ? <p>{data.greeting}</p> : <p>Loading..</p>}</div>
            <p>{JSON.stringify(sesion)}</p>
            <p>{secret.data}</p>
          </div>
        )}
      </div>
    </>
  );
};

export default Home;
