name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

  FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
  FLY_APP: ${{ secrets.FLY_APP }}

  KEYCLOAK_BASE_URL: ${{ secrets.KEYCLOAK_BASE_URL }}
  KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
  KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
  KEYCLOAK_ISSUER: ${{ secrets.KEYCLOAK_ISSUER }}

  NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
  NEXT_PUBLIC_SYNCFUSION_LICENSE_KEY: ${{ secrets.NEXT_PUBLIC_SYNCFUSION_LICENSE_KEY }}

  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.7.0'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: '7.9.0'
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build
        run: |
          pnpm install
          pnpm run lint
          pnpm run build

      - name: Deploy
        run: |
          flyctl deploy --local-only
