name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_APP: ${{ secrets.FLY_APP }}
  KEYCLOAK_BASE_URL: ${{ secrets.KEYCLOAK_BASE_URL }}
  KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
  KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
  KEYCLOAK_ISSUER: ${{ secrets.KEYCLOAK_ISSUER }}
  NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
  NEXT_PUBLIC_SYNCFUSION_LICENSE_KEY: ${{ secrets.NEXT_PUBLIC_SYNCFUSION_LICENSE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'

      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: '7.9.0'

      - name: setup fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: build
        run: |
          pnpm install
          pnpm run lint
          pnpm run build

      - name: deploy
        run: |
          flyctl deploy --local-only
