name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - uses: pnpm/action-setup@v2.2.2
      
      - name: install fly
        run: curl -L https://fly.io/install.sh | sh

      - name: build
        run: |
          pnpm run lint
          pnpm run build
